/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java`
    `java-library`
    `maven-publish`
    `signing` // pour signer les artefacts, requis pour Maven Central
}


publishing {
    publications.create<MavenPublication>("test_maven") {
        from(components["java"])
    }

    repositories {
        mavenLocal()
        maven {
            name = "ossrh"
            url = uri("https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/")
            credentials {
                val user = project.properties["ossrhUsername"]
                val password = project.properties["ossrhPassword"]
            }
        }
    }
}
signing {
    sign(publishing.publications["test_maven"])
}











group = "io.github.edemairy"
version = "0.0.1-SNAPSHOT"
description = "Maven core"
java.sourceCompatibility = JavaVersion.VERSION_1_8


